from oscar.apps.catalogue.categories import create_from_breadcrumbs

categories = [
    "Exterior Accessories > Body Kits & Ground Effects > Spoilers",
    "Exterior Accessories > Body Kits & Ground Effects > Lip Kits",
    "Exterior Accessories > Body Kits & Ground Effects > Side Skirts",
    "Exterior Accessories > Bumpers & Grilles > Front Bumpers",
    "Exterior Accessories > Bumpers & Grilles > Rear Bumpers",
    "Exterior Accessories > Bumpers & Grilles > Grilles",
    "Exterior Accessories > Mirrors > Side Mirrors",
    "Exterior Accessories > Mirrors > Rearview Mirrors",
    "Wheels & Tires > Wheels",
    "Wheels & Tires > Tires",
    "Wheels & Tires > Hubcaps",
    "Wheels & Tires > Tire Accessories",
    "Wheels & Tires > Tire Pressure Monitoring Systems (TPMS)",
    "Performance Parts > Air Intake & Filters",
    "Performance Parts > Exhaust Systems",
    "Performance Parts > Suspension & Steering",
    "Performance Parts > Brakes",
    "Performance Parts > Engine Components",
    "Performance Parts > Transmission Parts",
    "Tools & Garage > Hand Tools",
    "Tools & Garage > Power Tools",
    "Tools & Garage > Garage Organization",
    "Tools & Garage > Car Care Products",
    "Tools & Garage > Diagnostic Tools",
    "Electronics & Accessories > Car Audio & Video",
    "Electronics & Accessories > GPS & Navigation",
    "Electronics & Accessories > Radar Detectors",
    "Electronics & Accessories > Car Alarms & Security",
    "Electronics & Accessories > Dash Cams",
    "Motorcycle Parts & Accessories > Helmets & Apparel",
    "Motorcycle Parts & Accessories > Engine Parts",
    "Motorcycle Parts & Accessories > Exhausts",
    "Motorcycle Parts & Accessories > Tires & Wheels",
    "Motorcycle Parts & Accessories > Luggage & Storage",
    "Truck Parts & Accessories > Bed Liners & Covers",
    "Truck Parts & Accessories > Running Boards & Nerf Bars",
    "Truck Parts & Accessories > Tonneau Covers",
    "Truck Parts & Accessories > Hitches & Towing",
    "Truck Parts & Accessories > Off-Road Accessories",
    "HeadLigts and Lightning > Turn Signals",
    "HeadLigts and Lightning > Fog Ligts",
    "HeadLigts and Lightning > Headligts > Lights",
    "Interior Parts > Fog Mats",
    "Interior Parts > Gauges",
    "Interior Parts > Steering Wheel",
    "Interior Parts > Cargo Accessories",
    "Repair Manual",
    "Fuel SYstem",
]

for breacrumb in categories:
    create_from_breadcrumbs(breacrumb)

print("Categories successfully added.")
