# Generated by Django 5.2.4 on 2025-08-17 16:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('shops', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('featured_products', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The main title for the hero section.', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'The descriptive text under the title.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text for the call-to-action button.', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL for the call-to-action button.', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_text', 2), ('button_link', 3), ('background_image', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Title for the featured products section, e.g., 'New Arrivals'.", 'required': True}), 7: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['catalogue.Product'], 'required': True}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('products', 8)]], {})})),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_pages', to='shops.shop')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
