# Generated by Django 5.2.4 on 2025-07-26 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Code can be used to store a secondary unique identifier, when upc isn't sufficient"),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.SmallIntegerField(db_index=True, default=0, help_text='The highest priority products are shown first', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Priority'),
        ),
    ]
