name: Django CI/CD

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # If you have submodules

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install needed packages (if any)
        run: sudo apt-get install -y exiftool libgraphviz-dev # Example packages

      - name: Install/Update uv
        uses: astral-sh/setup-uv@v3

      - name: Synchronize dependencies with uv
        run: uv sync

      - name: Deploy to DigitalOcean (Master Branch Only)
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ghaction-ssh@master
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            ssh... "
              set -e
              cd /var/www/prod/tuuziane
              source /var/www/envs/tuuziane/bin/activate
              git pull origin main
              uv sync --active
              python manage.py migrate
              python manage.py collectstatic --noinput
              sudo systemctl restart your-gunicorn-service # Or supervisorctl...
              echo "Deployment to tuuziane.com successful!"
            "

      - name: Check application health (version check)
        if: github.ref == 'refs/heads/master'
        run: |
          curl -s https://tuuziane.com/api/version/ | grep "\"version\":" # Or your health check method
          if [ $? -ne 0 ]; then
            echo "Health check failed!"
            exit 1
          else
            echo "Health check passed!"
          fi
